using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WFHMonitor.Models;

public enum TestCaseStatus
{
    Pass,
    Fail,
    Pending,
    Skip
}

public enum TestCaseCategory
{
    All,
    Smoke,
    Regression,
    UAT
}

public enum TestCaseEnvironment
{
    Dev,
    Staging,
    UAT,
    Production
}

public class TestCase
{
    public int Id { get; set; }

    [Required, MaxLength(20)]
    public string TestNumber { get; set; } = string.Empty;

    [Required, MaxLength(300)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(4000)]
    public string? Description { get; set; }

    [MaxLength(200)]
    public string? Module { get; set; }

    public TestCaseStatus Status { get; set; } = TestCaseStatus.Pending;
    public TestCaseCategory Category { get; set; } = TestCaseCategory.All;
    public TestCaseEnvironment Environment { get; set; } = TestCaseEnvironment.Dev;

    [ForeignKey(nameof(ChangeRequest))]
    public int? ChangeRequestId { get; set; }
    public ChangeRequest? ChangeRequest { get; set; }

    [ForeignKey(nameof(LinkedBug))]
    public int? LinkedBugId { get; set; }
    public BugReport? LinkedBug { get; set; }

    [ForeignKey(nameof(CreatedBy))]
    public string CreatedById { get; set; } = string.Empty;
    public ApplicationUser? CreatedBy { get; set; }

    public bool IsAutoGenerated { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
