export type UnknownRecord = Record<string, unknown>;

export interface ApiRedirect {
  controller?: string | null;
  action?: string | null;
  routeValues?: UnknownRecord | null;
  url?: string | null;
}

export interface ApiEnvelope<T> {
  data: T;
  errors: Record<string, string[]>;
  success?: string | null;
  error?: string | null;
  redirect?: ApiRedirect | null;
}

export interface RuntimeAccess {
  canViewAllProjects: boolean;
  canModifyAllProjects: boolean;
  canViewFeatures: boolean;
  canModifyFeatures: boolean;
  canViewBugs: boolean;
  canModifyBugs: boolean;
  canViewQaTesting: boolean;
  canModifyQaTesting: boolean;
  bellNotificationSoundEnabled: boolean;
  bellNotificationSoundOption: string;
}

export interface NotificationItem {
  id: number;
  title: string;
  message: string;
  linkUrl?: string | null;
  isRead: boolean;
  createdAt: string;
}

export interface NotificationBell {
  unreadCount: number;
  items: NotificationItem[];
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  photoUrl?: string | null;
  companyName?: string | null;
  plan: string;
  hasProAccess: boolean;
}

export interface BootstrapResponse {
  isAuthenticated: boolean;
  antiForgeryToken: string;
  user?: UserProfile | null;
  roles: string[];
  access: RuntimeAccess;
  notifications: NotificationBell;
  isGitHubOAuthConfigured: boolean;
  isGitHubConnected: boolean;
}

export interface SelectOption {
  value: string;
  text: string;
  selected?: boolean;
  disabled?: boolean;
}

export interface ApplicationUser {
  id: string;
  userName?: string | null;
  email?: string | null;
  fullName: string;
  profilePhotoPath?: string | null;
  companyName?: string | null;
  createdAt: string;
  isActive: boolean;
  subscriptionPlan: string;
  isProSubscriptionActive: boolean;
  proSubscribedAt?: string | null;
  proSubscriptionEndsAt?: string | null;
  isProCancelAtPeriodEnd: boolean;
  organizationTeam: string;
  orgTeamId?: number | null;
  orgTeam?: { id: number; name: string } | null;
  lastActivityAt?: string | null;
}

export interface StoredFile extends UnknownRecord {
  id: number;
  fileName: string;
  originalFileName?: string | null;
  caption?: string | null;
  uploadedAt?: string | null;
}

export interface ProjectFeature extends UnknownRecord {
  id: number;
  changeRequestId: number;
  featureNumber: string;
  name: string;
  description?: string | null;
  moduleImpacted?: string | null;
  linkedBugs?: string | null;
  pullRequestUrl?: string | null;
  status: string;
  priority: string;
  stage: string;
  timelineStart?: string | null;
  timelineEnd?: string | null;
  assignedDeveloper?: ApplicationUser | null;
  assignedDeveloperId?: string | null;
  agentStatus: string;
  agentImplementationPlan?: string | null;
  isCompleted: boolean;
  isAutoDetected: boolean;
  screenshots?: StoredFile[];
}

export interface ChangeRequest extends UnknownRecord {
  id: number;
  crNumber: string;
  title: string;
  description?: string | null;
  status: string;
  priority: string;
  stage: string;
  timelineStart?: string | null;
  timelineEnd?: string | null;
  githubRepoUrl?: string | null;
  githubBranch?: string | null;
  technologyStack?: string | null;
  projectHealthScore?: number | null;
  projectHealthLabel?: string | null;
  bugScanStatus?: string;
  createdAt: string;
  updatedAt: string;
  createdBy?: ApplicationUser | null;
  features?: ProjectFeature[];
  archSpecImages?: StoredFile[];
  documents?: StoredFile[];
}

export interface BugReport extends UnknownRecord {
  id: number;
  bugNumber: string;
  title: string;
  description?: string | null;
  workflow?: string | null;
  stepsToReproduce?: string | null;
  moduleImpacted?: string | null;
  pullRequestUrl?: string | null;
  severity: string;
  status: string;
  agentStatus: string;
  assignedDeveloper?: ApplicationUser | null;
  assignedAgent?: ApplicationUser | null;
  changeRequest?: ChangeRequest | null;
  screenshots?: StoredFile[];
  documents?: StoredFile[];
  createdAt: string;
  updatedAt: string;
}

export interface TestCase extends UnknownRecord {
  id: number;
  testNumber: string;
  name: string;
  description?: string | null;
  module?: string | null;
  status: string;
  category: string;
  environment: string;
  changeRequest?: ChangeRequest | null;
  linkedBug?: BugReport | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}
